version: '3'

volumes:
  django_sample_db_dev: {}

services:
  db:
    image: postgres
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=journey_db
      - POSTGRES_USER=pmcarlos
      - POSTGRES_PASSWORD=Carlap/91
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=journey_db
      - DJANGO_DB_USERNAME=pmcarlos
      - DJANGO_DB_PASSWORD=Carlap/91
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8001:8000"
    command:
      - bash
      - -c
      - |
        python manage.py migrate
        python manage.py runserver 0:8000
    restart: always
    volumes:
      - ./:/app/
    depends_on:
      - db
    links:
      - db
